apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
favorite:
  drink:{{ .Values.favorite.drink}}
  food:{{ .Values.favorite.food}}
  place:{{ .Values.favorite.place}}